### ISSUE TITLE
ComfyUI IPAdapter error 

### ISSUE THREAD

**Issue by Berdan232** [CosmicLaca/ComfyUI_Primere_Nodes#1]
Hello, I have been using ComfyUI for a few days now and I keep getting an error message with the IPAdapter and I don't know why. It says 'NoneType object has no attribute "encode_image"' and I couldn't find a solution. It's very urgent, does anyone know how to fix this problem?
<img width="1280" alt="problem IPA" src="https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/154834728/60e59395-8878-4d8c-8e87-341789a43216">

**Comment by CosmicLaca** [comment]
Hi, this is not my node, I cant help.
