### ISSUE TITLE
Cannot import ComfyUI_Primere_Nodes module for custom nodes: pyexiv2

### ISSUE THREAD

**Issue by dfl** [CosmicLaca/ComfyUI_Primere_Nodes#11]
this is really weird because my python version is 3.11
is it a bug with pyexiv2 ?

```
Traceback (most recent call last):
  File "/Users/dfl/sd/ComfyUI/nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/dfl/sd/ComfyUI/custom_nodes/ComfyUI_Primere_Nodes/__init__.py", line 7, in <module>
    from .Nodes import Inputs
  File "/Users/dfl/sd/ComfyUI/custom_nodes/ComfyUI_Primere_Nodes/Nodes/Inputs.py", line 11, in <module>
    from .modules.image_meta_reader import ImageExifReader
  File "/Users/dfl/sd/ComfyUI/custom_nodes/ComfyUI_Primere_Nodes/Nodes/modules/image_meta_reader.py", line 4, in <module>
    import pyexiv2
  File "/Users/dfl/sd/ComfyUI/venv/lib/python3.11/site-packages/pyexiv2/__init__.py", line 6, in <module>
    from .core import *
  File "/Users/dfl/sd/ComfyUI/venv/lib/python3.11/site-packages/pyexiv2/core.py", line 1, in <module>
    from .lib import exiv2api
  File "/Users/dfl/sd/ComfyUI/venv/lib/python3.11/site-packages/pyexiv2/lib/__init__.py", line 14, in <module>
    raise RuntimeError('pyexiv2 only supports these Python versions: {} . But your version is {} .'.format(expected_py_version, py_version))
RuntimeError: pyexiv2 only supports these Python versions: ['3.5', '3.6', '3.7', '3.8', '3.9'] . But your version is 3.1 .

Cannot import /Users/dfl/sd/ComfyUI/custom_nodes/ComfyUI_Primere_Nodes module for custom nodes: pyexiv2 only supports these Python versions: ['3.5', '3.6', '3.7', '3.8', '3.9'] . But your version is 3.1 .
```

**Comment by drphero** [comment]
That error looks very weird because pyexiv2 definitely doesn't only support those python versions. Inside the site-packages/pyexiv2-2.12.0.dist-info directory, there should be a file called WHEEL. Mine has a line that says "Tag: cp310-none-win_amd64". That means it used pyexiv2-2.12.0-cp310-none-win_amd64.whl, which is good because I'm using 3.10.11. What does yours say?

**Comment by drphero** [comment]
Looking further into that error message, it comes pyexiv2/lib/__init__.py and the last version to have exactly that message was 2.7.0 a few years ago. Version 2.12.0 would list `['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']` as the supported python versions. So I suspect that if you activate your venv and run `pip show pyexiv2`, it will show your version as 2.7.0.

If that's the case, try `pip install --force-reinstall -v "pyexiv2==2.12.0"` and hopefully you'll be all set.

**Comment by dfl** [comment]
```
(venv) (base) ➜  ComfyUI git:(master) ✗ venv/bin/pip3 show pyexiv2                                                                
Name: pyexiv2
Version: 2.5.0
Summary: Read/Write metadata(including EXIF, IPTC, XMP), comment and ICC Profile embedded in digital images.
Home-page: https://github.com/LeoHsiao1/pyexiv2
Author: LeoHsiao
Author-email: leohsiao@foxmail.com
License: GPLv3
Location: /Users/dfl/sd/ComfyUI/venv/lib/python3.11/site-packages
Requires: 
Required-by: 

(venv) (base) ➜  ComfyUI git:(master) ✗ venv/bin/pip install --force-reinstall -v "pyexiv2==2.12.0"
Using pip 24.0 from /Users/dfl/sd/ComfyUI/venv/lib/python3.11/site-packages/pip (python 3.11)
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
ERROR: Ignored the following yanked versions: 2.4.0, 2.6.0
ERROR: Could not find a version that satisfies the requirement pyexiv2==2.12.0 (from versions: 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0, 2.0.0, 2.1.0, 2.2.0, 2.3.0, 2.3.1, 2.3.2, 2.4.1, 2.5.0)
ERROR: No matching distribution found for pyexiv2==2.12.0
```

**Comment by drphero** [comment]
That's really weird because when looking at the pypi index it's using at https://pypi.org/simple/pyexiv2/, I can see that there are four 2.12.0 versions listed for python 3.11.

Based on your directory structure, it looks like you are using a mac. Is that right? If so, what is your OS version and is it using an Intel chip or M1/M2/M3?

**Comment by dfl** [comment]
it's M3 Sonoma 14.2.1
If I had to guess it would be some kind of conflict between homebrew/conda and venv. But I don't see any proof of that...

anyhow, thanks for your attempted help!

**Comment by drphero** [comment]
I just tried to install it on my M1 mac and it is also grabbing 2.5.0. One thing you might try is first uninstalling the old version with `pip uninstall pipexiv2` then cloning `https://github.com/LeoHsiao1/pyexiv2` and build/install it with `pip install .` from inside the newly cloned pyexiv2 directory and with your comfyui venv activated.

**Comment by drphero** [comment]
I just tried this myself and it looks like it won't be that easy. I'll need to try to compile exiv2 from source as well.

**Comment by dfl** [comment]
I have exiv2 installed from homebrew, but it doesn't have built-in python bindings....

**Comment by CosmicLaca** [comment]
@dfl @drphero As I see the exif reader not working in Mac? :( Maybe another exif reader/writer lib helps, I will try soon.

**Comment by CosmicLaca** [comment]
@dfl I think the new fork will solve the problem. I will do a short test and if all right will out soon the solution. Thanks for @kaneda2004

**Comment by kaneda2004** [comment]
> @dfl I think the new fork will solve the problem. I will do a short test and if all right will out soon the solution. Thanks for @kaneda2004

No worries - yes the PR I made uses a different library to solve the issue of piexiv2 not being able to be built on Mac OS - by using a different library compatible with ARM Macs.
