### ISSUE TITLE
So much of value, but some glaring QOL issues

### ISSUE THREAD

**Issue by Ainaemaet** [CosmicLaca/ComfyUI_Primere_Nodes#15]
This node pack is pretty wonderful for the most part - a lot of useful stuff here (thank you). 

Unfortunately, my main reason behind wanting to use it is for the visual checkpoint/lora loading, and the restrictions and tediousness of the setup just makes it something that I don't want to bother with  - especially considering all of the work that already goes into crafting  a good workflow! 

The hard JPG limit on the previews is terrible; especially given that many people use the Auto1111 [Civitai Browser +](https://github.com/BlafKing/sd-civitai-browser-plus) extension to download and organize their models; so the best thing for _this_ ComfyUI_Primere_Nodes pack, would be if it could utilize the already existing previews (png) and model-info, as downloaded and saved from CivitaiBrowser+ extension. 

Pythongosssss ['ComfyUI-Custom-Scripts'](https://github.com/pythongosssss/ComfyUI-Custom-Scripts) does this, which makes bouncing back and forth between setups a breeze; and while you include some of their nodes in  your workflows, the fact that their checkpoint/lora loader can utilize the already existing .png previews _with no need to  move files around_ is a huge Godsend, and one that makes that nodepack considerably more useful atm. 

Please implement similar (or better) functionality into ComfyUI_Primere_Nodes - it would make this undeniably one of the best packs available out there for ComfyUI.

**Comment by CosmicLaca** [comment]
I merged today @JonathanWac's solution for accepting more file formats, and if no loading time issue because large files from Civitai, I will found some new solution to read images from existing model directories.
