### ISSUE TITLE
The node is not working after the CompyUI update.

### ISSUE THREAD

**Issue by Neytiri7** [CosmicLaca/ComfyUI_Primere_Nodes#2]
I've tried reinstalling several times, but it doesn't work the same way.
It shows that you have not been imported at all.

`Traceback (most recent call last):
  File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\__init__.py", line 11, in <module>
    from .Nodes import Segments
  File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\Nodes\Segments.py", line 7, in <module>
    from ..components import detectors
  File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\components\detectors.py", line 20, in <module>
    from .local_groundingdino.datasets import transforms as T
ModuleNotFoundError: No module named 'ComfyUI_Primere_Nodes.components.local_groundingdino'`

`Cannot import O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes module for custom nodes: No module named 'ComfyUI_Primere_Nodes.components.local_groundingdino'`

 `1.0 seconds (IMPORT FAILED): O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes`

**Comment by CosmicLaca** [comment]
> I've tried reinstalling several times, but it doesn't work the same way. It shows that you have not been imported at all.
> 
> `Traceback (most recent call last): File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\nodes.py", line 1810, in load_custom_node module_spec.loader.exec_module(module) File "<frozen importlib._bootstrap_external>", line 940, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\__init__.py", line 11, in <module> from .Nodes import Segments File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\Nodes\Segments.py", line 7, in <module> from ..components import detectors File "O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\components\detectors.py", line 20, in <module> from .local_groundingdino.datasets import transforms as T ModuleNotFoundError: No module named 'ComfyUI_Primere_Nodes.components.local_groundingdino'`
> 
> `Cannot import O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes module for custom nodes: No module named 'ComfyUI_Primere_Nodes.components.local_groundingdino'`
> 
> `1.0 seconds (IMPORT FAILED): O:\AI\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes`

True, the new push failed. Repair soon.

**Comment by Neytiri7** [comment]
Normal operation.
Thank you.

Happy New Year.
