### ISSUE TITLE
Image Meta Saver doesn't embed the workflow.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [CosmicLaca/ComfyUI_Primere_Nodes#25]
As the title says. I have the option enabled), but the flow is not embedded.
![image](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/52193044/052e1a8a-157e-4693-97b8-aea1b0bbeb3a)

This is the output file...
![GTM_20242905_162923_1](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/52193044/9feaf124-752e-4a36-b0e4-bc21bf66c73d)

When dragged into ComfyUI...
![image](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/52193044/c6b79ad8-595e-4c57-bc53-aa8cf4647ae7)

**Comment by GalaxyTimeMachine** [comment]
It's been 2 weeks. Have you seen this bug?

**Comment by CosmicLaca** [comment]
> It's been 2 weeks. Have you seen this bug?

Hi, sorry for the long delay. Upgrade and try now, in my env working with png.
