### ISSUE TITLE
Unobtainable recommended seg models

### ISSUE THREAD

**Issue by Qbiccx** [CosmicLaca/ComfyUI_Primere_Nodes#3]
I have been searching hugging face and the comfy manager for like an hour, but I can't find the following recommended segm models:
- facial_features_yolo8x-seg (maybe one of these two? https://huggingface.co/jxy/yolo8x/tree/main https://huggingface.co/arnabdhar/YOLOv8-Face-Detection/tree/main)
- flower_seg_yolov8model (only flower_yolov5 https://huggingface.co/models?sort=trending&search=flower_yolov)
- yolov8_butterfly_custom (Only this, is it the same? https://huggingface.co/imageomics/butterfly_segmentation_yolo_v8/tree/main)
- yolov8l-seg (only yolov8l.pt, is it the same? https://huggingface.co/kadirnar/yolov8l-v8.0/tree/main)
- yolov8m-seg(only yolov8m.pt, is it the same? https://huggingface.co/kadirnar/yolov8m-v8.0/tree/main)
- yolov8n-seg(only yolov8m.pt, is it the same? https://huggingface.co/kadirnar/yolov8n-v8.0/tree/main)
- yolov8s-seg(only yolov8m.pt, is it the same? https://huggingface.co/ultralyticsplus/yolov8s/tree/main)
- yolov8x-seg(only yolov8m.pt, is it the same? https://huggingface.co/kadirnar/yolov8x-v8.0/tree/main)

Any suggestions?

**Comment by CosmicLaca** [comment]
Here are the most important models: https://huggingface.co/jags/yolov8_model_segmentation-set/tree/main but the universal with labels: https://huggingface.co/ultralyticsplus/yolov8s/tree/main

**Comment by Qbiccx** [comment]
Thanks a  lot, I don't know why the search function didnt pick those up, I was searching for the exact file names.
