### ISSUE TITLE
Warning: Missing Node Types  When loading the graph, the following node types were not found:  PrimereRefinerPrompt & PrimereImageSegments

### ISSUE THREAD

**Issue by Vigilence** [CosmicLaca/ComfyUI_Primere_Nodes#31]
Using latest Comfyui.  Fully updated.

![Screenshot 2024-08-20 060251](https://github.com/user-attachments/assets/759f5066-fc1b-4ae4-ae4c-00e8092ee781)

**Comment by CosmicLaca** [comment]
@Vigilence as I see the problem solved. Please check it.

**Comment by Vigilence** [comment]
@CosmicLaca  It works!  Thank you!
