### ISSUE TITLE
[Feature Request] Kwai-Kolors Support

### ISSUE THREAD

**Issue by Vigilence** [CosmicLaca/ComfyUI_Primere_Nodes#32]
I would love to use these workflows with Kwai-kolors.  Minus-zone is my go to node pack for kolors and somewhat works with inspire and impact nodes but have issues with hand refiner.  It includes a patch to use and sdxl controlnet model.

**Comment by CosmicLaca** [comment]
@Vigilence Supported, on basic workflow the concept selector node working with Kolors too :)
![2024-10-22_12-09-28](https://github.com/user-attachments/assets/f8f6373f-5262-46fd-9bc4-4868ab470e55)
