### ISSUE TITLE
IMPORT FAILED 

### ISSUE THREAD

**Issue by Simoxys** [CosmicLaca/ComfyUI_Primere_Nodes#35]
I tried updating Comfy, updating/installing lightning, I have no idea anymore.
[comfyuilog.txt](https://github.com/user-attachments/files/16832286/comfyuilog.txt)

||||||||||||||||||||||||||||||||||||||||||

C:\Users\simox\Documents\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-02 00:37:59.960618
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\Users\simox\Documents\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI
** Log path: C:\Users\simox\Documents\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 31950 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\web
C:\Users\simox\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Error:
[WinError 1314] A required privilege is not held by the client: 'C:\\Users\\simox\\Documents\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'C:\\Users\\simox\\Documents\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals\js
Target: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['C:\\Users\\simox\\Documents\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'C:\\Users\\simox\\Documents\\ComfyUI_windows_portable\\ComfyUI\\models\\animatediff_models']
Adding C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V7.4.1)
Loaded ImpactPack nodes from C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
Bmad-DirtyUndoRedo Loaded.
Skip C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
[Crystools INFO] Crystools version: 1.16.6
[Crystools INFO] CPU: AMD Ryzen 9 7945HX with Radeon Graphics - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090 Laptop GPU
[Crystools INFO] NVIDIA Driver: 560.81
[ComfyUI-Easy-Use] server: v1.2.2 Loaded
[ComfyUI-Easy-Use] web root: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
### Loading: ComfyUI-Impact-Pack (V7.4.1)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.1)
jjk_util loding
Total VRAM 16376 MB, total RAM 31950 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
### ComfyUI Revision: 2641 [f1c23016] | Released on '2024-09-01'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
A new version of Albumentations is available: 1.4.14 (you have 1.4.11). Upgrade using: pip install --upgrade albumentations
[ReActor] - STATUS - Running v0.5.1-a6 in ComfyUI
Torch version: 2.4.0+cu121
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
[09/02/24 00:38:08] WARNING  Your inference package version 0.9.13 is out of date! Please upgrade to      __init__.py:35
                             version 0.17.0 of inference for the latest features and bug fixes by running
                             `pip install --upgrade inference`.
SupervisionWarnings: BoundingBoxAnnotator is deprecated: `BoundingBoxAnnotator` is deprecated and has been renamed to `BoxAnnotator`. `BoundingBoxAnnotator` will be removed in supervision-0.26.0.
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
A new version of Albumentations is available: 1.4.14 (you have 1.4.11). Upgrade using: pip install --upgrade albumentations
# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
# 😺dzNodes: LayerStyle -> Warning: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Find 1 LUTs in C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\lut
# 😺dzNodes: LayerStyle -> Find 1 Fonts in C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\font
Traceback (most recent call last):
  File "C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\__init__.py", line 7, in <module>
    from .Nodes import Dashboard
  File "C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\Nodes\Dashboard.py", line 21, in <module>
    from ..components import clipping
  File "C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\components\clipping.py", line 2, in <module>
    from .long_clip_model import longclip
  File "C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\components\long_clip_model\longclip.py", line 6, in <module>
    from pkg_resources import packaging
ImportError: cannot import name 'packaging' from 'pkg_resources' (C:\Users\simox\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py)

Cannot import C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes module for custom nodes: cannot import name 'packaging' from 'pkg_resources' (C:\Users\simox\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py)
[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 83 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
---------------------------------- Prompt Generator ComfyUI Node -----------------------------------
/_\ Checking packages
/_\ Installing optimum-quanto
/_\ Loading Prompt Generator
/_\ Loaded Successfully
----------------------------------------------------------------------------------------------------

[rgthree] Loaded 42 fantastic nodes.
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.

Searge-SDXL v4.3.1 in C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Every artist was first an amateur." - Ralph Waldo Emerson

Import times for custom nodes:
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\gcLatentTunnel.py
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\LoadLoraWithTags
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds (IMPORT FAILED): C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\lora-info
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-plasma
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Jjk-Nodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Lora-Auto-Trigger-Words
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Saver
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\primitive-types
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Static-Primitives
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ComfyWorkflows
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SizeFromPresets
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-propost
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\lazy-pony-prompter
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\virtuoso-nodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds (IMPORT FAILED): C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
   0.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.1 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.1 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.4 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.6 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.7 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.7 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui
   0.8 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.8 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   1.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
   1.0 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   1.2 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
   1.2 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.4 seconds: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\prompt-generator-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
BilboX LUTs path set to: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
BilboX LUTs path set to: C:\Users\simox\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts

**Comment by CosmicLaca** [comment]
@Simoxys as I see by google search `pip install setuptools==69.5.1 helps`. Python module problem.

**Comment by Simoxys** [comment]
i tried that, but it wasn't successful. it works with a completely new download but i dont think that helps any

**Comment by CosmicLaca** [comment]
@Simoxys I think solved the module import problem. Can you try?
