### ISSUE TITLE
Images Missing Despite Correct Placement and Resizing

### ISSUE THREAD

**Issue by ArareF** [CosmicLaca/ComfyUI_Primere_Nodes#36]
Hello,
I hope this message finds you well. I encountered an issue while using the plugin. I followed the instructions, placing the images into the correct folders and subfolders, and resized all the images to a maximum width and height of 220px (in jpg format). Most of the images display correctly, but there are still a few that show as missing. Do you have any suggestions on what might be causing this?
![image](https://github.com/user-attachments/assets/b5f3b349-0126-4a86-ab1e-83f96f655363)

**Comment by CosmicLaca** [comment]
@ArareF Can you give me example filenames of failed lora/preview? Maybe some character for example spaces. The image saver node save previews to right path and name if the process done.
![2024-09-23_07-58-23](https://github.com/user-attachments/assets/79d2c25f-65f2-47df-9f4a-e8b54b5e6e0b)
