### ISSUE TITLE
selector?

### ISSUE THREAD

**Issue by 4lt3r3go** [CosmicLaca/ComfyUI_Primere_Nodes#38]
when i tryed first time i got the menu with all networks showing, but then trying it today i coudnt achieve that anymore.
how to properly open that visual menu?

**Comment by CosmicLaca** [comment]
@4lt3r3go Unfortunately full nodepack under re-development. Only the features (nodes) of minimal workflow working. If really important the older version, roll back using git, and upgrade by the content of readme.md This time only the checkpoint and csv prompt visual menu working.

**Comment by 4lt3r3go** [comment]
thanks for your time! 🙏
