### ISSUE TITLE
DynamicParser Node strange behavior

### ISSUE THREAD

**Issue by BlackVortexAI** [CosmicLaca/ComfyUI_Primere_Nodes#41]
I have two problems with the DynamicParser Node:

1. the node used to be able to evaluate nested prompts, e.g.

`{A closeup Image of a {man he|woman she} is {sitting on a {bench|chair} | A image of a libary}`

However, I am now getting incorrect output. Like this output:

`A Closeup Image of a chair | A image of a libary}`

2. despite the seed remaining the same, the prompt I receive changes.

Am I making a mistake or is this a bug?

Greetings BV

**Comment by CosmicLaca** [comment]
@BlackVortexAI Hi, here is the official syntax doc of dynamic prompt parser: https://github.com/adieyal/sd-dynamic-prompts/blob/main/docs/SYNTAX.md, I just implemented this. I dont think that you can include dynamic syntax within another dynamic syntax like in first example. As I remember (I used intensively) for same seed the output is same, but I will check soon.
