### ISSUE TITLE
PrimereImageSegments.primere_segments() missing 1 required positional argument: 'segment_prompt_data'

### ISSUE THREAD

**Issue by hiowenluke** [CosmicLaca/ComfyUI_Primere_Nodes#8]
```
Error occurred when executing PrimereImageSegments:

PrimereImageSegments.primere_segments() missing 1 required positional argument: 'segment_prompt_data'

File "D:\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
```
<img width="1440" alt="capture2" src="https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/19872828/fbed7238-6be2-4feb-9ad9-a5bb0d917bc1">

**Comment by CosmicLaca** [comment]
Hi [hiowenluke], the node already updated. The 'PROMPT_DATA' from refiner prompt node must be connected to Image segments. Just pull and refresh the node.

**Comment by hiowenluke** [comment]
I tried, but the 'PROMPT_DATA' can be only connect to segmeng_settings in Primere Any Detailer, and the error is still exists.

<img width="1704" alt="image" src="https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/19872828/b5d14c9f-a4e3-4879-b366-bfe372029c8e">

The workflow is below:
[workflow.json](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/files/14473993/workflow.json)

**Comment by CosmicLaca** [comment]
@hiowenluke Something wrong in attached workflow, 'prompt_data' must be connected to the image segment node, like in the pic. But I attach my development workflow, tested before uploaded, and working well in my environment.
![2024-03-03_19-46-13](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/7955114/6bbb4fd3-f1e7-4ea3-a311-9555a0311809)
[refiner_dev.json](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/files/14474199/refiner_dev.json)

**Comment by CosmicLaca** [comment]
@hiowenluke Finally I checked you attached workflow. Something outdated I think, you must re-create all old anodes (after git pull on my nodepack and comfy root too). 

- First re-create all nodes by the right-click menu -> Fix node (recreate)
![2024-03-04_08-37-04](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/7955114/75d8650d-c539-4f1b-bbf7-0acd893bbd0e)

- Then re-wire the workflow, or use my attached repaired new json
[repaired_workflow.json](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/files/14478382/repaired_workflow.json)

I tested for hair, and succeed with Sd and SDXL checkpoints too:

![2024-03-04_09-05-42](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/7955114/768f91c7-f8fe-4aa0-8869-5c79b6c23a14)
![2024-03-04_08-53-30](https://github.com/CosmicLaca/ComfyUI_Primere_Nodes/assets/7955114/e16c3fe2-4d2d-475a-92e9-ebbd2319a3fb)

**Comment by hiowenluke** [comment]
It works.
Thanks.
